blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://twitter.com/gingerbeardman
    about: Please ask and answer questions here
  - name: Great Wave Today
    url: https://greatwavetoday.com
    about: View the current site
