name: 🌊 New Impression
description: If your Gallery/Museum has an original impression that is not listed
title: "[NEW]: "
labels: ["new"]
assignees:
  - gingerbeardman
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form! |
        In order for your impression to be added our automation needs to be able to check the status through a web page.
  - type: input
    id: org
    attributes:
      label: Organisation name
      description: The name of your gallery or museum
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: online
    attributes:
      label: Online collection?
      description: In order for us to track your collection it needs to be available online
      options:
        - label: collection is online
          required: false
  - type: checkboxes
    id: onview
    attributes:
      label: On view status visible?
      description: In order for us to track view status it needs to be visible online
      options:
        - label: on view status is visible
          required: false
  - type: checkboxes
    id: original
    attributes:
      label: Original impression?
      description: We do not track impressions that were produced after Hokusai's death 
      options:
        - label: we have an original impression
          required: false
